services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: time-payment-timescaledb
    environment:
      POSTGRES_USER: tp_user
      POSTGRES_PASSWORD: tp_pass
      POSTGRES_DB: time_payment
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    command: >
      postgres
      -c shared_preload_libraries=timescaledb,pg_stat_statements
      -c pg_stat_statements.track=all
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c wal_level=logical
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tp_user -d time_payment"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  timescale_data:
